export const BgShoes = [
  {
    imagen: 'https://canariaskidshoes.com/wp-content/uploads/2019/03/274548-deportivos-de-nino-azul-pablosky-de-piel.jpg',
    tallas: ['20', '21', '22', '23', '24'],
    descripcion: 'Zapatilla deportiva para niños, color azul con detalles en verde, estilo casual.',
    precio: 29.99,
  },
  {
    imagen: 'https://i.pinimg.com/originals/25/e0/66/25e066ae5ada5ce7293f659c17563232.jpg',
    tallas: ['22', '23', '24', '25', '26'],
    descripcion: 'Sandalia rosa con diseño floral, ideal para niñas, estilo veraniego.',
    precio: 34.99,
  },
  {
    imagen: 'https://freesoldier.com/cdn/shop/products/512s2imtYpL_5a7c0905-3e58-409e-bae5-5782e6945a77.jpg?v=1677806885&width=500',
    tallas: ['24', '25', '26', '27', '28'],
    descripcion: 'Botas para niños en color negro, diseño resistente para el invierno.',
    precio: 39.99,
  },
  {
    imagen: 'https://static.dafiti.com.co/p/brash-2228-6499012-2-zoom.jpg',
    tallas: ['21', '22', '23', '24', '25'],
    descripcion: 'Zapatillas brillantes para niñas, color plateado, perfectas para fiestas.',
    precio: 31.99,
  },
  {
    imagen: 'https://calzamundo.com.co/wp-content/uploads/2023/08/Escolar-507-GJ599090-A.png',
    tallas: ['23', '24', '25', '26', '27'],
    descripcion: 'Zapatos escolares para niños, color negro, estilo clásico.',
    precio: 28.99,
  },
  {
    imagen: '',
    tallas: ['25', '26', '27', '28', '29'],
    descripcion: 'Botines elegantes para niñas, color rosa pastel, perfectos para ocasiones especiales.',
    precio: 45.99,
  },
  {
    imagen: '',
    tallas: ['20', '21', '22', '23', '24'],
    descripcion: 'Zapatilla deportiva para niños, color verde con detalles en amarillo, estilo deportivo.',
    precio: 32.99,
  },
  {
    imagen: '',
    tallas: ['22', '23', '24', '25', '26'],
    descripcion: 'Sandalia con estampado de leopardo, ideal para niñas, estilo salvaje.',
    precio: 37.99,
  },
  {
    imagen: '',
    tallas: ['24', '25', '26', '27', '28'],
    descripcion: 'Botas de lluvia para niños, color azul marino, diseño divertido con dinosaurios.',
    precio: 24.99,
  },
  {
    imagen: '',
    tallas: ['21', '22', '23', '24', '25'],
    descripcion: 'Zapatillas con luces LED para niños, color negro, perfectas para la diversión nocturna.',
    precio: 42.99,
  },
  {
    imagen: '',
    tallas: ['23', '24', '25', '26', '27'],
    descripcion: 'Zapatos de tela para niños, diseño a rayas, ideales para primavera.',
    precio: 29.99,
  },
  {
    imagen: '',
    tallas: ['25', '26', '27', '28', '29'],
    descripcion: 'Botines con detalles metálicos para niñas, color dorado, estilo moderno.',
    precio: 49.99,
  },
  {
    imagen: '',
    tallas: ['20', '21', '22', '23', '24'],
    descripcion: 'Zapatilla deportiva para niños, color rojo con detalles en negro, estilo deportivo.',
    precio: 36.99,
  },
  {
    imagen: '',
    tallas: ['22', '23', '24', '25', '26'],
    descripcion: 'Sandalia con flores en relieve, ideal para niñas, estilo primaveral.',
    precio: 33.99,
  },
  {
    imagen: '',
    tallas: ['24', '25', '26', '27', '28'],
    descripcion: 'Botas de nieve para niños, color blanco con detalles en azul, diseño invernal.',
    precio: 44.99,
  },
  {
    imagen: '',
    tallas: ['21', '22', '23', '24', '25'],
    descripcion: 'Zapatillas con velcro para niños, color verde limón, fáciles de poner y quitar.',
    precio: 27.99,
  },
  {
    imagen: '',
    tallas: ['23', '24', '25', '26', '27'],
    descripcion: 'Zapatos casuales para niños, color marrón, estilo versátil para uso diario.',
    precio: 38.99,
  },
  {
    imagen: '',
    tallas: ['25', '26', '27', '28', '29'],
    descripcion: 'Botines de terciopelo para niñas, color morado, perfectos para eventos especiales.',
    precio: 47.99,
  },
  {
    imagen: '',
    tallas: ['20', '21', '22', '23', '24'],
    descripcion: 'Zapatilla deportiva para niños, color naranja con detalles en blanco, estilo moderno.',
    precio: 35.99,
  },
  {
    imagen: '',
    tallas: ['22', '23', '24', '25', '26'],
    descripcion: 'Sandalia con diseño de estrellas, ideal para niñas, estilo celestial.',
    precio: 32.99,
  },
  {
    imagen: '',
    tallas: ['24', '25', '26', '27', '28'],
    descripcion: 'Botas de cuero para niños, color negro, diseño clásico y duradero.',
    precio: 54.99,
  },
  {
    imagen: '',
    tallas: ['21', '22', '23', '24', '25'],
    descripcion: 'Zapatillas con estampado de camuflaje para niños, color verde militar, estilo urbano.',
    precio: 39.99,
  },
  {
    imagen: '',
    tallas: ['23', '24', '25', '26', '27'],
    descripcion: 'Zapatos con brillos para niñas, color plateado, ideales para ocasiones especiales.',
    precio: 43.99,
  },
  {
    imagen: '',
    tallas: ['25', '26', '27', '28', '29'],
    descripcion: 'Botas de montaña para niños, color gris, ideales para actividades al aire libre.',
    precio: 49.99,
  },
  {
    imagen: '',
    tallas: ['21', '22', '23', '24', '25'],
    descripcion: 'Zapatillas con luces LED para niñas, color rosa, perfectas para la diversión nocturna.',
    precio: 42.99,
  },
  {
    imagen: '',
    tallas: ['23', '24', '25', '26', '27'],
    descripcion: 'Zapatos de tela para niños, diseño a rayas, ideales para primavera.',
    precio: 29.99,
  },
  {
    imagen: '',
    tallas: ['25', '26', '27', '28', '29'],
    descripcion: 'Botines con detalles metálicos para niñas, color dorado, estilo moderno.',
    precio: 47.99,
  },
  {
    imagen: '',
    tallas: ['20', '21', '22', '23', '24'],
    descripcion: 'Zapatilla deportiva para niños, color rojo con detalles en negro, estilo deportivo.',
    precio: 36.99,
  },
  {
    imagen: '',
    tallas: ['22', '23', '24', '25', '26'],
    descripcion: 'Sandalia con flores en relieve, ideal para niñas, estilo primaveral.',
    precio: 33.99,
  },
  {
    imagen: '',
    tallas: ['24', '25', '26', '27', '28'],
    descripcion: 'Botas de nieve para niños, color blanco con detalles en azul, diseño invernal.',
    precio: 44.99,
  },
];

